export const FETCH_DEPARTMENTS = "FETCH_DEPARTMENTS"
export const ADD_DEPARTMENT = "ADD_DEPARTMENT"
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT"
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT"